name: Check Dependencies
on:
  push:
    branches: [development]

jobs:
  create-pull-request-hub:
    runs-on: macos-11
    steps:
      - name: Setup github
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"

      - name: Setup brew
        run: brew install hub

      - name: Update dependencies
        run: |
          npx -p npm-check-updates ncu -u
          npm install

      - name: Create Pull Request
        run: |
          git config --global user.email "matheus.bertoldosi@gmail.com"
          git config --global user.name "bertoldosi"

          git checkout -b update-dependencies
          git commit -am "[ASN-000] Update Dependencies"

          hub pull-request -b origin update-dependencies
